apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lv56725pz-nodejs
  janus-idp.io/tekton: lv56725pz-nodejs
  backstage.io/kubernetes-id: lv56725pz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lv56725pz-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
