apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lv56725pz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lv56725pz-nodejs 
  name: lv56725pz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lv56725pz-nodejs 
